version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ticket-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: ticketuser
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:9
    container_name: ticket-flyway
    depends_on:
      - db
    command: >
      -url=jdbc:postgresql://db:5432/ticketdb
      -user=ticketuser
      -password=secret
      -locations=filesystem:/flyway/sql
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

volumes:
  db-data: